### ISSUE TITLE
Failed to receive SOCKS5 connect request ack.

### ISSUE THREAD

**Issue by FarhadMohseni** [xosad/Insta-mass-account-creator#11]
im using some socks5,s with authentication , after i added them to proxy.txt and calling the script , 
its saying Failed to receive SOCKS5 connect request ack.

**Comment by xosad** [comment]
https://github.com/xosad/Insta-mass-account-creator/blob/3869007c537129999a1fc394e90f950d72c675a2/InstaAccountBot.php#L146

under this line please add;

```php
curl_setopt($ch, CURLOPT_PROXYUSERPWD, user:pass);
```


**_I'll implement proxy user pass in the next update._**
