### ISSUE TITLE
Proxy list

### ISSUE THREAD

**Issue by denmasgie** [xosad/Insta-mass-account-creator#13]
Do you have a good recommendation for using a proxy?

**Comment by xosad** [comment]
Any <b>residential socks5 proxy</b>.

**Comment by denmasgie** [comment]
It doesnt print on account.json/not print

Pada Sabtu, 23 November 2019, Baran <notifications@github.com> menulis:
> Closed #13.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/WuqTzWnshjCuVhjS7LeeoWZpfyHe3gz0Ab-cLi_VeE1APLCyOxGwWRqV8KJ9A4e1qLYuJvu9tTrirz9YDZTZUoIw4RmoPufu2_Fnas51Py3RicvCNhXyifO_sBF6rYFi3wl95PdvG8iaBUWtpCY07tFcmy0KeJnNliR1WiCok-FUjTF5X3CUhcxLl-475gweOu21vLvb1YdwZaF0NwFiQWrGxSCrUe6rJZ9SdOS7YL3_lCHlNswH9xJ-ergRSy4=s0-d-e1-ft#https://github.com/notifications/beacon/AHWQQFTCZL56A6DCQRK7HWDQVBYFRA5CNFSM4JQXNGS2YY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOVBQRF3I.gif
>

-- 
Mei Giyanto

**Comment by xosad** [comment]
if the account is not created it won't print. Can you create accounts?

**Comment by denmasgie** [comment]
It's time consuming when processing(generate),I have run the php command
start.php + arg according to the documentation No account warnings have
been made after completing the process generate.I have repeated the steps
several times and I hope there is a print in the account.json file.But the
results are empty

Pada Sabtu, 23 November 2019, Baran <notifications@github.com> menulis:
> if the account is not created it won't print. Can you create accounts?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/SrM2M3Sj9RPC2o2xiziXsEFnQc6IDTsmq0DkE5c8NgnyMl91dg6n5t1WLUfFfH5SSNyYZCZeqC4WgHFaC78QUwpY1IFDf8za3uVFre8UsGpM-XqZVjXwWxbd4VntLPs5Gii2BKs8sW0SiqejTrKSau_pby947ijAbm3rhukrmwSy-dhy-E4Uh6Owy9XPqUKze5LzUJjGjj1JZp5_71oSo7qJ-2rtpA0P8N5q0gMihw=s0-d-e1-ft#https://github.com/notifications/beacon/AHWQQFW6N3GZU3DTFVUWW3LQVDUIPA5CNFSM4JQXNGS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE7QSHY.gif
>

-- 
Mei Giyanto

**Comment by denmasgie** [comment]
And I still don't understand. Is the sock5 that I used is the original or I
put the proxies.txt file wrong

Pada Sabtu, 23 November 2019, Baran <notifications@github.com> menulis:
> if the account is not created it won't print. Can you create accounts?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci5.googleusercontent.com/proxy/SrM2M3Sj9RPC2o2xiziXsEFnQc6IDTsmq0DkE5c8NgnyMl91dg6n5t1WLUfFfH5SSNyYZCZeqC4WgHFaC78QUwpY1IFDf8za3uVFre8UsGpM-XqZVjXwWxbd4VntLPs5Gii2BKs8sW0SiqejTrKSau_pby947ijAbm3rhukrmwSy-dhy-E4Uh6Owy9XPqUKze5LzUJjGjj1JZp5_71oSo7qJ-2rtpA0P8N5q0gMihw=s0-d-e1-ft#https://github.com/notifications/beacon/AHWQQFW6N3GZU3DTFVUWW3LQVDUIPA5CNFSM4JQXNGS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE7QSHY.gif
>

-- 
Mei Giyanto

**Comment by xosad** [comment]
Can you write here exactly how you run the command? e.g. `php start.php -l 4 -p proxies.txt`

<b> Every line should have one proxy e.g. </b>

```
101.162.13.96:9654
123.453.34.12:8080
```

### If it doesn't print out anything it means your proxies are dead most probably.

**Comment by denmasgie** [comment]
can you suggest where I can get a proxy.Because the proxy that I am looking
for in a Google search might be inaccurate

Pada Minggu, 24 November 2019, Baran <notifications@github.com> menulis:
> Can you write here exactly how you run the command? e.g. php start.php -l
4 -p proxies.txt
>
> Every line should have one proxy e.g.
>
> 101.162.13.96:9654
> 123.453.34.12:8080
>
> If it doesn't print out anything it means your proxies are dead most
probably.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.<
https://ci3.googleusercontent.com/proxy/xTj93esckmpIWhmKVCHutKDDP9QlZJQJexazvJRQAxWzkB0Kzlp2VQQE_8zo8yDkZPYrb6AYG078pkiBR4HNRVrGC8RmhQiebtOi8-Y9T8O3MkjR5n5Nma34IiN86YLoQchY4wDo15PF4lXKegMTSiE6CBunNlZqr_yJuK3T1n4f2JQjeSlwGKMYvQAUwrWoGdHcPOzJkpXPWbl0m_qnQlrOfwTyyIpTyTXsL1uVvA=s0-d-e1-ft#https://github.com/notifications/beacon/AHWQQFU72CHD3OWW5ENKNJ3QVFZPLA5CNFSM4JQXNGS2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEE73ACA.gif
>

-- 
Mei Giyanto

**Comment by webqart** [comment]
Add function getProxy to class igGenerator and use anywhere

**_$randUserProxy = $this -> getProxy($this -> proxy_file);_**

CURLOPT_PROXYPORT => $randUserProxy[1],
CURLOPT_PROXYTYPE => CURLPROXY_HTTP,
CURLOPT_PROXY => $randUserProxy[0],
CURLOPT_PROXYUSERPWD => $randUserProxy[2] . ':' . $randUserProxy[3]

Example: proxies.txt
ip:port:login:pass

[https://gist.github.com/webqart/c29b65963bf6557cc602526080cfa370](https://gist.github.com/webqart/c29b65963bf6557cc602526080cfa370)

**Comment by thsanki** [comment]
> Add function getProxy to class igGenerator and use anywhere
> 
> **_$randUserProxy = $this -> getProxy($this -> proxy_file);_**
> 
> CURLOPT_PROXYPORT => $randUserProxy[1],
> CURLOPT_PROXYTYPE => CURLPROXY_HTTP,
> CURLOPT_PROXY => $randUserProxy[0],
> CURLOPT_PROXYUSERPWD => $randUserProxy[2] . ':' . $randUserProxy[3]
> 
> Example: proxies.txt
> ip:port:login:pass
> 
> https://gist.github.com/webqart/c29b65963bf6557cc602526080cfa370

Bro tell me Command how to do that
