### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by ohhpea** [xosad/Insta-mass-account-creator#15]
where do i put my proxies
![Capture](https://user-images.githubusercontent.com/58167509/69528585-c157f980-0f2b-11ea-8a04-97bfa366a526.PNG)

**Comment by xosad** [comment]
`php start.php -p PATH_TO_PROXIES`

e.g. `php start.php -p proxies.txt`

**Comment by ohhpea** [comment]
i dont understand
