### ISSUE TITLE
Why generateClientId and generateCsrfToken passed without proxy?

### ISSUE THREAD

**Issue by beshoo** [xosad/Insta-mass-account-creator#16]
Hi
While reviewing the script details I note that if I am using a proxy , these functions used without the proxy.

```
			$this->generateClientId();
			$this->generateCsrfToken();
			$this->getAccountData();
```
**generateClientId** and **generateCsrfToken** use Instagram session, why don't you use the proxy to call thease exnd points.

and why we can not use the normal HTTP proxy, why you strick proxy to sokcs5 type?

**Comment by xosad** [comment]
That's a good point, i added the proxy mode later on and forgot about that requests. I'll fix that when i have time, and about your question why SOCKS5 and not HTTP proxy.


> SOCKS performs at a lower level than HTTP proxies: SOCKS takes advantage of handshake protocol to report the proxy software about the connection the client attempts to make and so operates as transparently as possible while an HTTP proxy could interpret and copy headers (for instance to invoke another underlying protocol, such as File Transfer Protocol (FTP). Nevertheless an HTTP proxy normally forwards an HTTP request to the eligible HTTP server). Although an HTTP proxy has a variant model in mind, the CONNECT method permits forwarding TCP connections. Nevertheless SOCKS proxies may work in reverse and forward UDP traffic while HTTP proxies can’t. HTTP proxies usually are more aware of the HTTP protocol and they perform higher-level filtering. However that normally only applies to POST and GET methods but not the CONNECT method.

**Comment by xosad** [comment]
Fixed the issue now the functions are using the proxy 

940053a802571ec0398a171d01d8888cf62d7fcc

**Comment by beshoo** [comment]
Thanks for the updates, but at least did you test if this script still
works?
