### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by h3llH0undX** [xosad/Insta-mass-account-creator#17]
Generating Instagram Account!
PHP Warning:  Use of undefined constant CURLOPT_FOLLOWLOCATION - assumed 'CURLOPT_FOLLOWLOCATION' (this will throw an Error in a future version of PHP) in /root/Desktop/Insta-mass-account-creator-master/start.php on line 19
PHP Warning:  Use of undefined constant CURLOPT_TCP_NODELAY - assumed 'CURLOPT_TCP_NODELAY' (this will throw an Error in a future version of PHP) in /root/Desktop/Insta-mass-account-creator-master/start.php on line 19
PHP Warning:  Use of undefined constant CURLOPT_FORBID_REUSE - assumed 'CURLOPT_FORBID_REUSE' (this will throw an Error in a future version of PHP) in /root/Desktop/Insta-mass-account-creator-master/start.php on line 19
PHP Warning:  Use of undefined constant CURLOPT_RETURNTRANSFER - assumed 'CURLOPT_RETURNTRANSFER' (this will throw an Error in a future version of PHP) in /root/Desktop/Insta-mass-account-creator-master/start.php on line 19
PHP Warning:  Use of undefined constant CURLOPT_POST - assumed 'CURLOPT_POST' (this will throw an Error in a future version of PHP) in /root/Desktop/Insta-mass-account-creator-master/start.php on line 19
PHP Warning:  Use of undefined constant CURLOPT_ENCODING - assumed 'CURLOPT_ENCODING' (this will throw an Error in a future version of PHP) in /root/Desktop/Insta-mass-account-creator-master/start.php on line 19
PHP Notice:  Undefined index: l in /root/Desktop/Insta-mass-account-creator-master/start.php on line 19
PHP Notice:  Undefined index: p in /root/Desktop/Insta-mass-account-creator-master/start.php on line 19
PHP Fatal error:  Uncaught Error: Call to undefined function xosad\curl_init() in /root/Desktop/Insta-mass-account-creator-master/src/xosad/igGenerator.php:123
Stack trace:
#0 /root/Desktop/Insta-mass-account-creator-master/src/xosad/igGenerator.php(147): xosad\igGenerator->getAccountData()
#1 /root/Desktop/Insta-mass-account-creator-master/start.php(20): xosad\igGenerator->generateInstagramAccount()
#2 {main}
  thrown in /root/Desktop/Insta-mass-account-creator-master/src/xosad/igGenerator.php on line 123

**Comment by xosad** [comment]
check if curl is installed correctly.

**Comment by LePetitHackerOff** [comment]
Y have same probleme im upgrade curl but still same error
