### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LePetitHackerOff** [xosad/Insta-mass-account-creator#21]
![Schermopname (2)](https://user-images.githubusercontent.com/52930346/70922839-136dd580-2027-11ea-8548-4b692ced3893.png)

**Comment by LePetitHackerOff** [comment]
Problem solved i change the proxies list name but now y run no error its say Generating Instagram Account ! and then it exit but the account.json is empty

**Comment by LePetitHackerOff** [comment]
why do you close it ?

**Comment by LePetitHackerOff** [comment]
the account.json still empty

**Comment by kaex** [comment]
This was fixed in the new release.
