### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LePetitHackerOff** [xosad/Insta-mass-account-creator#22]
Y run no error its say Generating Instagram Account ! and then it exit but the account.json is empty

**Comment by xosad** [comment]
I already closed your last issue? You are not giving me any information. Take a video or a picture. If you don't ask clearly i can't help you.

**Comment by LePetitHackerOff** [comment]
Y use this command 
![Schermopname (10)](https://user-images.githubusercontent.com/52930346/70929598-b9bfd800-2033-11ea-9260-d518d2e92c7f.png)

It work but when I choose option 1 he writes:
![Schermopname (11)](https://user-images.githubusercontent.com/52930346/70929615-c5130380-2033-11ea-809e-c383c65d6725.png)

and y find nothing in the account.json file

**Comment by xosad** [comment]
I answered on your other issue.
