### ISSUE TITLE
Problem whit account creating

### ISSUE THREAD

**Issue by LePetitHackerOff** [xosad/Insta-mass-account-creator#23]
Y use this command 
![Schermopname (10)](https://user-images.githubusercontent.com/52930346/70929598-b9bfd800-2033-11ea-9260-d518d2e92c7f.png)

It work but when I choose option 1 he writes:
![Schermopname (11)](https://user-images.githubusercontent.com/52930346/70929615-c5130380-2033-11ea-809e-c383c65d6725.png)

and y find nothing in the account.json file

**Comment by xosad** [comment]
Stop opening new ISSUES use the old ones.

**Comment by LePetitHackerOff** [comment]
ok but please help me

**Comment by LePetitHackerOff** [comment]
Im have this probleme:
![Schermopname (13)](https://user-images.githubusercontent.com/52930346/70930576-d0672e80-2035-11ea-9985-5fc19e331bb5.png)

**Comment by LePetitHackerOff** [comment]
Im used git clone https://github.com/xosad/Insta-mass-account-creator
then y use
![Schermopname (11)](https://user-images.githubusercontent.com/52930346/70930784-48355900-2036-11ea-9bdb-3b3a7e276f9b.png)
but it give this:
![Schermopname (17)](https://user-images.githubusercontent.com/52930346/70930883-85015000-2036-11ea-9974-96ec7d12a3b4.png)
