### ISSUE TITLE
curl_exec() return null

### ISSUE THREAD

**Issue by Tkd-Alex** [xosad/Insta-mass-account-creator#25]
Hi, thanks for your work! 
I want to try the script but the cur_exec() return null.

`if($request == null) echo("is null!");`
https://github.com/xosad/Insta-mass-account-creator/blob/master/src/xosad/igGenerator.php#L243

![image](https://user-images.githubusercontent.com/14061593/71415447-10449c00-265c-11ea-9f84-56c8ef325ff4.png)

Have you any ideas how to handle this?

**Comment by xosad** [comment]
Can i have the output for this

```
curl -X POST -d ''  https://www.instagram.com/accounts/web_create_ajax/ -v
```

**Comment by Tkd-Alex** [comment]
I've add this on the top of the code:
```php
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```

One of the problems it's that the script read the proxy without strip the **\n** and try to set-up to curl a proxy with new line...

**Comment by Tkd-Alex** [comment]
With one proxy I've no problem related to the php code

**Comment by xosad** [comment]
> I've add this on the top of the code:
> 
> ```
> ini_set('display_errors', 1);
> ini_set('display_startup_errors', 1);
> error_reporting(E_ALL);
> ```
> 
> One of the problems it's that the script read the proxy without strip the **\n** and try to set-up to curl a proxy with new line...

Send me the error
