### ISSUE TITLE
No accounts created

### ISSUE THREAD

**Issue by nihalashetty** [xosad/Insta-mass-account-creator#27]
I have used socks proxy but json file shows empty, i.e no accounts are getting created. please help me with this.
and sometimes it never terminates.

**Comment by GramCreator** [comment]
Try mobile/residential proxies.

**Comment by xosad** [comment]
There is some issues with instagram api i'll have a look.

**Comment by nihalashetty** [comment]
Is the issue got resolved?

**Comment by kaex** [comment]
This issue was fixed. There is a new issue with instagram follow here #55
