### ISSUE TITLE
Account Created

### ISSUE THREAD

**Issue by yekayee** [xosad/Insta-mass-account-creator#30]
this script error ? sucess created account but there is no in instagram. 
im using socks 5

{"created":true,"username":"blackfrog640krx","password":"123xosad123","email":"blackfrog640krx@gmail.com","name":"M\u00e1rcia Gon\u00e7alves"}

**Comment by xosad** [comment]
Instagram got strict with there user creation, i'll have a look when i have time.

**Comment by yekayee** [comment]
later u fix this ?
