### ISSUE TITLE
Termux no response

### ISSUE THREAD

**Issue by thsanki** [xosad/Insta-mass-account-creator#32]
![Screenshot_2020-01-07-22-00-46-53_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/59386036/71911172-3fe5bf00-3199-11ea-980c-bc1ab6cf5a75.png)

**Comment by thsanki** [comment]
![Screenshot_2020-01-07-22-01-01-85_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/59386036/71911201-4d9b4480-3199-11ea-86e6-caeac84e4722.png)

No account created why please tell brother

**Comment by xosad** [comment]
Have you tried reading [README.md](https://github.com/xosad/Insta-mass-account-creator#arguments) ?

**Comment by thsanki** [comment]
> Have you tried reading [README.md](https://github.com/xosad/Insta-mass-account-creator#arguments) ?

Yes but please tell me where i put the file proxies.txt please please of a make tutorial video brother its help alot
