### ISSUE TITLE
what is this??

### ISSUE THREAD

**Issue by zhir-dev** [xosad/Insta-mass-account-creator#35]
i got this 
{"created":true,"username":"krx","password":"123xosad123","email":"krx@gmail.com","name":" "}

why the username is "krx" and email is "krx@gmail.com" ??

**Comment by thsanki** [comment]
> i got this
> {"created":true,"username":"krx","password":"123xosad123","email":"[krx@gmail.com](mailto:krx@gmail.com)","name":" "}
> 
> why the username is "krx" and email is "[krx@gmail.com](mailto:krx@gmail.com)" ??

Bro can you tell how you set proxies please bro

**Comment by xosad** [comment]
> i got this
> {"created":true,"username":"krx","password":"123xosad123","email":"[krx@gmail.com](mailto:krx@gmail.com)","name":" "}
> 
> why the username is "krx" and email is "[krx@gmail.com](mailto:krx@gmail.com)" ??

There is a issue with reaching `https://randomuser.me/api/`, try using a proxy.

**Comment by xosad** [comment]
> > i got this
> > {"created":true,"username":"krx","password":"123xosad123","email":"[krx@gmail.com](mailto:krx@gmail.com)","name":" "}
> > why the username is "krx" and email is "[krx@gmail.com](mailto:krx@gmail.com)" ??
> 
> Bro can you tell how you set proxies please bro

README.md has everything you need.
