### ISSUE TITLE
Nothing's happening when trying to create account

### ISSUE THREAD

**Issue by Lil-Pepe** [xosad/Insta-mass-account-creator#36]
When I'm trying to create an account nothing is happening :
```
C:\Users\xxx\Desktop\Insta-mass-account-creator-master>php start.php -l 1 -p proxies.txt
Please choose a number.
1. Generate instagram accounts.
2. Follow instagram accounts with generated accounts.
1
[H[JGenerating Instagram Account!

C:\Users\xxx\Desktop\Insta-mass-account-creator-master>
```
The bot stucks on the `[H[JGenerating Instagram Account!` then the last line appear to tell that the process is done.

Thanks!

**Comment by xosad** [comment]
Do you have the `proxies.txt` ?

**Comment by thsanki** [comment]
> Do you have the `proxies.txt` ?

Where to put the file proxies.txt
Please tell in which section..

**Comment by xosad** [comment]
> > Do you have the `proxies.txt` ?
> 
> Where to put the file proxies.txt
> Please tell in which section..

in the same directory as `start.php`

**Comment by thsanki** [comment]
> > > Do you have the `proxies.txt` ?
> > 
> > 
> > Where to put the file proxies.txt
> > Please tell in which section..
> 
> in the same directory as `start.php`

Brother can you make a video on it..how to put proxies and how it creates Account please brother❤️❤️
And upload it on YouTube or send your Instagram id i want to talk with you

**Comment by Zaakaria** [comment]
I have the same problem, and I do use proxy file

**Comment by rndt3k** [comment]
Same here, there's an issue with the Instagram. Idk if you can fix it.

**Comment by xosad** [comment]
Yes now days with the new instagram updates, it's really hard to sign up with an email + web API, <b>when i will have time</b> i'll update the API and send requests from mobile API.
