### ISSUE TITLE
Php file

### ISSUE THREAD

**Issue by bobthebuilder3** [xosad/Insta-mass-account-creator#37]
Im not realy a computer person and I just did this instagram mass account creator because it was free. Can someone please give tell me how to run php files?

**Comment by xosad** [comment]
you can start by typing `php start.php` to start generating accounts.

**Comment by VAGDDev** [comment]
Where to tipe? In Terminal?

**Comment by kaex** [comment]
@VAGDDev yes inside the repo folder run `php start.php` in the terminal.
