### ISSUE TITLE
[Error] clear' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by Abdulsamipy** [xosad/Insta-mass-account-creator#39]
hey , so i have been trying to start the file via cmd and it's saying 

`clear' is not recognized as an internal or external command, operable program or batch file.`

**Comment by niilopoutanen** [comment]
i have the same issue when trying to enter 1 to generate accounts

**Comment by xosad** [comment]
Try something like this the clear function won't work on CMD, https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/

**Comment by kaex** [comment]
This was fixed in the new release have a look. 

https://github.com/kaex/Insta-mass-account-creator/releases/tag/v0.2-stable
