### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by z1231z** [xosad/Insta-mass-account-creator#4]
ok...this time the bot is not sending request to instagram.com/accounts/web_create_ajax/
it only send request to randomuser.me/api/ and instagram.com/data/shared_data/
and it will give you " Proxy is dead! & curl_exec bool(false) "
it should send to instagram.com/accounts/web_create_ajax/ and gives you success or error...
but this part is not working...

**Comment by xosad** [comment]
@z1231z can you run the code and post the output here ? i have everything working
