### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by ho3einfaramarzi** [xosad/Insta-mass-account-creator#5]
Hello.
What kind of proxy should I use?
What site do i get?

**Comment by xosad** [comment]
Please read the[ README.md ](https://github.com/xosad/Insta-mass-account-creator/blob/master/README.md)

**> USE ONLY SOCKS 5 PROXY**

**Comment by ho3einfaramarzi** [comment]
Which site to find?

**Comment by ho3einfaramarzi** [comment]
i used this with proxy but error : {"account_created": false, "errors": {"ip": ["The IP address you are using has been flagged as an open proxy. If you believe this to be incorrect, please visit http://help.instagram.com/"]}, "status": "ok", "error_type": "signup_block"}

**Comment by xosad** [comment]
Yes buy some **private** proxies not **online** ones a lot of people use them.

**Comment by ho3einfaramarzi** [comment]
Which site to find?

**Comment by xosad** [comment]
search on **google**;` paid socks5 proxy`
