### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by ishandutta2007** [xosad/Insta-mass-account-creator#6]
- Which device id will it use, instagram is device id restricted, 5 account per device ?
- Is email account and its name as well as instagram username auto generated, if so how ?
- Can I use my current IP without using any proxy, for example my use-case is to login to a ec2 host and run this script from there without any proxy, will it work ? 

Sorry couldn't figure out from docs all these, so had to ask, maybe we can make the documentation more explicit going forward.

**Comment by xosad** [comment]
* it's creates account from web instagram not mobile api, so the only restriction is the ip limit to create account

**Comment by xosad** [comment]
* it's creates account from web instagram not mobile api, so the only restriction is the ip limit to create account

* everything is generated using the randomapi https://randomuser.me/api/

* if the proxy.txt file is empty or doesn't exist it will create using no proxy

**Comment by ishandutta2007** [comment]
thanks @xosad for answering, maybe for new users we can create a FAQ if you don't intend to overcrowd the main Readme page.

**Comment by ishandutta2007** [comment]
thanks @xosad for answering, maybe for new users we can create a FAQ if you don't intend to overcrowd the main Readme page.
> * it's creates account from web instagram not mobile api, so the only restriction is the ip limit to create account

Though I am not an expert but I have some doubts for this use-case though , I ma saying so because I have personally tried connecting my mac book to other wifi's apart from my home's but still couldn't create an account using chrome, I always get the message something went wrong no matter which wifi I connect to , I even tried incognito mode. so I am very sure they have my machine details already.

**Comment by xosad** [comment]
> Though I am not an expert but I have some doubts for this use-case though , I am saying so because I have personally tried connecting my mac book to other wifi's apart from my home's but still couldn't create an account using chrome, I always get the message something went wrong no matter which wifi I connect to , I even tried incognito mode. so I am very sure they have my machine details already.

When you create an instagram account directly from the instagram webpage, thats true it gets data about your machine but i give the necessary data for the sign-up nothing more, but give it a shot maybe i know it wrong maybe there might be something like that, and it will block the machine no matter what.

**Comment by ishandutta2007** [comment]
Didn't work(brand new proxy) 😢 
When did it work for you the last time? What you are saying is that you are not sending up any device id, isn't that same as incognito mode. Infact incognito mode used to work a year back , but now I get they reject any request which doesn't send a device id. You may have to spoof device id as well.

**Comment by xosad** [comment]
> Didn’t work(brand new proxy)

Can you please send me the error you got? If i’ll find free time i’ll double check the code. 2-3 month ago there was no issue but instagram might updated the requests.

**Comment by ishandutta2007** [comment]
> {"account_created": false, "errors": {"ip": ["The IP address you are using has been flagged as an open proxy. If you believe this to be incorrect, please visit http://help.instagram.com/"]}, "status": "ok", "error_type": "signup_block"}

**Comment by ishandutta2007** [comment]
For me this technique worked 6 months back, https://www.blackhatworld.com/seo/method-create-unlimited-instagram-accounts-through-your-desktop.828334/
It simulates new devices alongside dynamic IP. Now dynamic IP of 4G network is not working, So I have to keep buying proxy servers.(or setting up of own proxy server)

**Comment by xosad** [comment]
I'll double check this and get back to you here. 3 days ago before pushing the new release i was able to create instagram account with a private socks5 proxies.

**Comment by ishandutta2007** [comment]
@xosad Did you try it with a new IP?

**Comment by xosad** [comment]
> @xosad Did you try it with a new proxy?

I think there is a problem with the code i’ll check it out this friday and fix it

**Comment by ishandutta2007** [comment]
@xosad bro any luck. I am waiting for you, will buy new proxy only after you assure.

**Comment by xosad** [comment]
> @xosad bro any luck ? I'll wait for you, will buy new proxy only after you assure.

No still couldn't find the error, i tried it with python selenium still no success, i'll update when it's working just watch the repo

**Comment by ishandutta2007** [comment]
you mean [this](https://github.com/FeezyHendrix/Insta-mass-account-creator) script?

**Comment by xosad** [comment]
> you mean [this](https://github.com/FeezyHendrix/Insta-mass-account-creator) script?

same logic yes, but that doesn't work either same error as the one i'm getting in this repo

**Comment by ishandutta2007** [comment]
Let's keep aside the scripts for the time being.
Buddy, help me create a couple of accounts manually first.
I don't know what I am missing. I have dynamic IP (so actually I didn't need to buy proxy), secondly I am creating new virtual devices(tried with android emulator as well as bluestack), how are they still knowing my originals ?

**Comment by ishandutta2007** [comment]
any update ?
