### ISSUE TITLE
getting an error

### ISSUE THREAD

**Issue by Ahron333** [xosad/Insta-mass-account-creator#8]
i am getting an error when trying to run it line 72
![Screenshot_59](https://user-images.githubusercontent.com/37657144/65871218-9a93a180-e386-11e9-989e-e487a5b90baa.png)

**Comment by xosad** [comment]
Which branch are you using?

**Comment by Ahron333** [comment]
what is this branch ?

**Comment by Ahron333** [comment]
why did u close it?

**Comment by Ahron333** [comment]
please dude why u wont help
